      // ── MATERIA: INTELIGENCIA ARTIFICIAL ──
      // Generado a partir de "IA para Ingenieros: Primeros Pasos" (Ing. Brian Peñafiel Plata, UNIOR)
      const IA_TEMAS = ['TODOS', 'TEMA I'];
      const IA_SECCIONES = [
        'TODAS',
        '¿Qué es la IA?',
        '¿Cómo aprende la IA?',
        'Herramientas y lenguajes',
        'Proyecto primer modelo',
        'Desafíos y ética',
        'Actualidad',
      ];

      const IA_QUESTIONS = [
        // ── TEMA I: ¿Qué es la IA? ──
        {
          id: 'ia1',
          tema: 'TEMA I',
          seccion: '¿Qué es la IA?',
          text: '¿Cuáles son las tres capacidades principales que busca replicar la Inteligencia Artificial según su definición?',
          opts: ['Diseñar, fabricar y vender', 'Aprender, razonar y tomar decisiones', 'Programar, compilar y ejecutar', 'Almacenar, indexar y buscar'],
          answer: 1,
        },
        {
          id: 'ia2',
          tema: 'TEMA I',
          seccion: '¿Qué es la IA?',
          text: '¿Cuál de los siguientes es un ejemplo de IA Estrecha?',
          opts: [
            'Las recomendaciones de Netflix',
            'Una IA con habilidades cognitivas humanas en cualquier contexto',
            'Una IA capaz de superar la inteligencia humana',
            'Un sistema con conciencia propia',
          ],
          answer: 0,
        },
        {
          id: 'ia3',
          tema: 'TEMA I',
          seccion: '¿Qué es la IA?',
          text: 'La IA General se caracteriza por:',
          opts: [
            'Ser el tipo de IA que usamos a diario',
            'Ser hipotética, con habilidades cognitivas humanas en cualquier contexto',
            'Ser capaz de superar ampliamente la inteligencia humana',
            'Estar diseñada para tareas específicas como el streaming',
          ],
          answer: 1,
        },
        {
          id: 'ia4',
          tema: 'TEMA I',
          seccion: '¿Qué es la IA?',
          text: 'La IA Superinteligente se define como aquella capaz de:',
          opts: [
            'Superar la inteligencia humana, siendo objeto de debate ético y futurista',
            'Realizar únicamente tareas específicas y acotadas',
            'Aprender exclusivamente por refuerzo',
            'Sustituir por completo el trabajo humano en la actualidad',
          ],
          answer: 0,
        },
        {
          id: 'ia5',
          tema: 'TEMA I',
          seccion: '¿Qué es la IA?',
          text: "En el diagrama de Data Science, la intersección entre 'Math and Statistics' y 'Computer Science/IT' corresponde a:",
          opts: ['Applied Research', 'Domain Knowledge', 'Ad Hoc Technical Solution', 'Machine Learning'],
          answer: 3,
        },
        {
          id: 'ia6',
          tema: 'TEMA I',
          seccion: '¿Qué es la IA?',
          text: 'El nacimiento formal de la Inteligencia Artificial se sitúa en el año 1956 con:',
          opts: ['La creación de TensorFlow', 'El primer chatbot comercial', 'La Conferencia de Dartmouth', 'El lanzamiento de Python'],
          answer: 2,
        },
        {
          id: 'ia7',
          tema: 'TEMA I',
          seccion: '¿Qué es la IA?',
          text: "En la línea de tiempo de la IA, los 'Inviernos de la IA' se caracterizaron por:",
          opts: [
            'Los primeros programas de ajedrez',
            'El nacimiento de la IA en Dartmouth',
            'El auge por Big Data y la nube',
            'Crisis de financiación y expectativas',
          ],
          answer: 3,
        },
        {
          id: 'ia8',
          tema: 'TEMA I',
          seccion: '¿Qué es la IA?',
          text: 'El auge actual de la Inteligencia Artificial se explica principalmente por:',
          opts: [
            'La reducción del uso de datos',
            'La desaparición de los lenguajes de programación',
            'El abandono de las redes neuronales',
            'El Big Data y la disponibilidad de la nube',
          ],
          answer: 3,
        },
        {
          id: 'ia9',
          tema: 'TEMA I',
          seccion: '¿Qué es la IA?',
          text: "En el ciclo de vida de un sistema de IA, después de 'Datos de Entrenamiento' y 'Algoritmos' se obtiene:",
          opts: ['Una base de datos relacional', 'Un informe contable', 'Una interfaz gráfica', 'Un Modelo Predictivo'],
          answer: 3,
        },

        // ── TEMA II: ¿Cómo aprende la IA? ──
        {
          id: 'ia10',
          tema: 'TEMA I',
          seccion: '¿Cómo aprende la IA?',
          text: '¿Cuáles son los tres tipos principales de aprendizaje automático?',
          opts: [
            'Lineal, No lineal y Cuántico',
            'Rápido, Lento y Progresivo',
            'Supervisado, No Supervisado y por Refuerzo',
            'Manual, Automático y Semiautomático',
          ],
          answer: 2,
        },
        {
          id: 'ia11',
          tema: 'TEMA I',
          seccion: '¿Cómo aprende la IA?',
          text: 'En el Aprendizaje Supervisado, el primer paso del proceso es:',
          opts: ['Seleccionar el algoritmo', 'Validar y probar', 'Ajustar parámetros', 'Recolectar datos etiquetados'],
          answer: 3,
        },
        {
          id: 'ia12',
          tema: 'TEMA I',
          seccion: '¿Cómo aprende la IA?',
          text: 'Un ejemplo típico de Aprendizaje No Supervisado es:',
          opts: [
            'El agrupamiento (clustering) con K-means',
            'La clasificación con etiquetas conocidas',
            'El aprendizaje por refuerzo con recompensas',
            'La propagación hacia atrás en redes neuronales',
          ],
          answer: 0,
        },
        {
          id: 'ia13',
          tema: 'TEMA I',
          seccion: '¿Cómo aprende la IA?',
          text: 'En el Aprendizaje por Refuerzo, los tres elementos clave del proceso son:',
          opts: [
            'Agente IA, Entorno y Recompensa',
            'Dato, Algoritmo y Modelo',
            'Python, NumPy y pandas',
            'Entrenamiento, Predicción y Evaluación',
          ],
          answer: 0,
        },
        {
          id: 'ia14',
          tema: 'TEMA I',
          seccion: '¿Cómo aprende la IA?',
          text: 'El objetivo del Aprendizaje por Refuerzo es:',
          opts: [
            'Reducir el número de neuronas de la red',
            'Minimizar la cantidad de datos utilizados',
            'Eliminar por completo el error de entrenamiento',
            'Maximizar la recompensa acumulada a largo plazo',
          ],
          answer: 3,
        },
        {
          id: 'ia15',
          tema: 'TEMA I',
          seccion: '¿Cómo aprende la IA?',
          text: 'Las redes neuronales artificiales se inspiran en:',
          opts: ['Los sistemas operativos móviles', 'Las bases de datos relacionales', 'Las neuronas biológicas del cerebro', 'Los circuitos eléctricos domésticos'],
          answer: 2,
        },
        {
          id: 'ia16',
          tema: 'TEMA I',
          seccion: '¿Cómo aprende la IA?',
          text: 'El proceso mediante el cual una red neuronal ajusta sus pesos a partir del error se llama:',
          opts: ['Propagación hacia atrás (Backpropagation)', 'Propagación hacia adelante (Forward pass)', 'Escalado de datos', 'Codificación One-Hot'],
          answer: 0,
        },
        {
          id: 'ia17',
          tema: 'TEMA I',
          seccion: '¿Cómo aprende la IA?',
          text: 'Las funciones de activación en una red neuronal se caracterizan por ser:',
          opts: ['Siempre lineales', 'Exclusivas del aprendizaje supervisado', 'Innecesarias para el entrenamiento', 'No lineales'],
          answer: 3,
        },

        // ── TEMA III: Herramientas y lenguajes ──
        {
          id: 'ia18',
          tema: 'TEMA I',
          seccion: 'Herramientas y lenguajes',
          text: 'El lenguaje de programación que domina el ecosistema de la IA es:',
          opts: ['Java', 'PHP', 'Python', 'C++'],
          answer: 2,
        },
        {
          id: 'ia19',
          tema: 'TEMA I',
          seccion: 'Herramientas y lenguajes',
          text: 'Para empezar con Python en IA se recomienda instalar:',
          opts: ['AutoCAD', 'WordPress', 'Photoshop', 'Anaconda'],
          answer: 3,
        },
        {
          id: 'ia20',
          tema: 'TEMA I',
          seccion: 'Herramientas y lenguajes',
          text: 'Jupyter Notebook es una herramienta clave porque permite:',
          opts: [
            'Ejecutar código por celdas y visualizar resultados interactivamente',
            'Compilar programas en C++',
            'Diseñar interfaces gráficas de escritorio',
            'Administrar bases de datos relacionales',
          ],
          answer: 0,
        },
        {
          id: 'ia21',
          tema: 'TEMA I',
          seccion: 'Herramientas y lenguajes',
          text: 'NumPy es una librería que proporciona principalmente:',
          opts: [
            'Arrays eficientes y operaciones vectorizadas',
            'DataFrames para tablas de datos',
            'Modelos de deep learning preentrenados',
            'Visualización de gráficos interactivos',
          ],
          answer: 0,
        },
        {
          id: 'ia22',
          tema: 'TEMA I',
          seccion: 'Herramientas y lenguajes',
          text: 'pandas es una librería utilizada principalmente para:',
          opts: [
            'Gestionar servidores en la nube',
            'Crear interfaces web',
            'Manipular tablas de datos mediante DataFrames',
            'Entrenar redes neuronales profundas',
          ],
          answer: 2,
        },
        {
          id: 'ia23',
          tema: 'TEMA I',
          seccion: 'Herramientas y lenguajes',
          text: 'Scikit-learn permite entrenar y evaluar modelos de:',
          opts: [
            'Clasificación, regresión y clustering',
            'Únicamente redes neuronales convolucionales',
            'Bases de datos distribuidas',
            'Procesamiento de video en tiempo real',
          ],
          answer: 0,
        },
        {
          id: 'ia24',
          tema: 'TEMA I',
          seccion: 'Herramientas y lenguajes',
          text: 'TensorFlow es un framework desarrollado por:',
          opts: ['Apple', 'Google', 'Amazon', 'Microsoft'],
          answer: 1,
        },
        {
          id: 'ia25',
          tema: 'TEMA I',
          seccion: 'Herramientas y lenguajes',
          text: 'Keras se caracteriza por ser:',
          opts: [
            'Una interfaz de alto nivel que simplifica la definición de modelos',
            'Un lenguaje de programación de bajo nivel',
            'Una base de datos NoSQL',
            'Un sistema operativo para servidores',
          ],
          answer: 0,
        },

        // ── TEMA IV: Proyecto primer modelo ──
        {
          id: 'ia26',
          tema: 'TEMA I',
          seccion: 'Proyecto primer modelo',
          text: 'El primer paso en la planificación de un proyecto de IA es:',
          opts: ['Desplegar el sistema', 'Escalar los datos', 'Definir el problema', 'Entrenar el modelo'],
          answer: 2,
        },
        {
          id: 'ia27',
          tema: 'TEMA I',
          seccion: 'Proyecto primer modelo',
          text: 'Para explorar un dataset con pandas, la función que muestra estadísticas descriptivas es:',
          opts: ['df.hist()', 'df.info()', 'df.corr()', 'df.describe()'],
          answer: 3,
        },
        {
          id: 'ia28',
          tema: 'TEMA I',
          seccion: 'Proyecto primer modelo',
          text: 'La técnica utilizada para transformar variables categóricas en numéricas se llama:',
          opts: ['One-Hot Encoding', 'StandardScaler', 'train_test_split', 'Backpropagation'],
          answer: 0,
        },
        {
          id: 'ia29',
          tema: 'TEMA I',
          seccion: 'Proyecto primer modelo',
          text: 'El escalado de variables numéricas mediante StandardScaler tiene como objetivo:',
          opts: [
            'Eliminar variables categóricas',
            'Reducir el tamaño del dataset',
            'Aumentar el número de columnas',
            'Que las variables tengan la misma importancia',
          ],
          answer: 3,
        },
        {
          id: 'ia30',
          tema: 'TEMA I',
          seccion: 'Proyecto primer modelo',
          text: 'La función train_test_split se utiliza para:',
          opts: [
            'Visualizar la distribución de variables',
            'Entrenar el modelo final',
            'Separar los datos en conjuntos de entrenamiento y prueba',
            'Codificar variables categóricas',
          ],
          answer: 2,
        },
        {
          id: 'ia31',
          tema: 'TEMA I',
          seccion: 'Proyecto primer modelo',
          text: 'Para ajustar (entrenar) un modelo en Scikit-learn se utiliza el método:',
          opts: ['.describe()', '.predict(X_test)', '.fit(X_train, y_train)', '.score()'],
          answer: 2,
        },
        {
          id: 'ia32',
          tema: 'TEMA I',
          seccion: 'Proyecto primer modelo',
          text: 'Para generar predicciones sobre datos nuevos se utiliza el método:',
          opts: ['.hist()', '.fit(X_train, y_train)', '.predict(X_test)', '.describe()'],
          answer: 2,
        },
        {
          id: 'ia33',
          tema: 'TEMA I',
          seccion: 'Proyecto primer modelo',
          text: 'El coeficiente R² (coeficiente de determinación) indica:',
          opts: [
            'El número de capas de una red neuronal',
            'La velocidad de entrenamiento del modelo',
            'Qué proporción de la varianza en los datos es explicada por el modelo',
            'El número total de datos del dataset',
          ],
          answer: 2,
        },

        // ── TEMA V: Desafíos y ética ──
        {
          id: 'ia34',
          tema: 'TEMA I',
          seccion: 'Desafíos y ética',
          text: 'El desafío del sesgo en IA ocurre porque los modelos:',
          opts: [
            'Aprenden de datos históricos que pueden reflejar discriminaciones',
            'Nunca utilizan datos reales',
            'Solo funcionan con datos sintéticos',
            'No requieren de datos para entrenarse',
          ],
          answer: 0,
        },
        {
          id: 'ia35',
          tema: 'TEMA I',
          seccion: 'Desafíos y ética',
          text: "Las técnicas de 'fairness' en IA buscan:",
          opts: [
            'Aumentar la velocidad de procesamiento',
            'Construir sistemas de IA inclusivos y legales',
            'Eliminar el uso de estadística',
            'Reducir el tamaño de los modelos',
          ],
          answer: 1,
        },
        {
          id: 'ia36',
          tema: 'TEMA I',
          seccion: 'Desafíos y ética',
          text: 'Un riesgo de privacidad en sistemas de IA son los llamados:',
          opts: [
            'Errores de sintaxis en el código',
            'Fallos de conexión a internet',
            'Ataques de inferencia que reconstruyen información sensible',
            'Problemas de batería en dispositivos móviles',
          ],
          answer: 2,
        },
        {
          id: 'ia37',
          tema: 'TEMA I',
          seccion: 'Desafíos y ética',
          text: 'El Federated Learning es una solución de privacidad que permite:',
          opts: [
            'Eliminar la necesidad de entrenar modelos',
            'Entrenar modelos sin centralizar los datos',
            'Aumentar la exposición de datos sensibles',
            'Centralizar todos los datos en un único servidor',
          ],
          answer: 1,
        },
        {
          id: 'ia38',
          tema: 'TEMA I',
          seccion: 'Desafíos y ética',
          text: "El principio de 'Privacy by Design' implica:",
          opts: [
            'Delegar la privacidad únicamente al usuario final',
            'Ignorar la privacidad en el desarrollo',
            'Aplicar principios de privacidad desde el diseño del sistema',
            'Aplicar la privacidad solo después de un incidente',
          ],
          answer: 2,
        },
        {
          id: 'ia39',
          tema: 'TEMA I',
          seccion: 'Desafíos y ética',
          text: 'La Explicabilidad de la IA (XAI) busca principalmente:',
          opts: [
            'Ocultar el funcionamiento interno de los modelos',
            'Que los usuarios y reguladores entiendan las decisiones de la IA',
            'Reducir el número de datos necesarios',
            'Aumentar la velocidad de los modelos',
          ],
          answer: 1,
        },
        {
          id: 'ia40',
          tema: 'TEMA I',
          seccion: 'Desafíos y ética',
          text: 'Herramientas como SHAP y LIME se utilizan para:',
          opts: [
            'Recolectar datos de sensores IoT',
            'Generar explicaciones locales sobre qué variables influyeron en una predicción',
            'Entrenar redes neuronales más rápido',
            'Codificar variables categóricas',
          ],
          answer: 1,
        },
        {
          id: 'ia41',
          tema: 'TEMA I',
          seccion: 'Desafíos y ética',
          text: 'Respecto al futuro del trabajo, la automatización impulsada por IA:',
          opts: [
            'Elimina por completo la necesidad de trabajo humano',
            'Desplaza empleos rutinarios pero crea nuevos roles en desarrollo y supervisión de IA',
            'Solo afecta a los ingenieros de software',
            'No afecta a ningún sector laboral',
          ],
          answer: 1,
        },
        {
          id: 'ia42',
          tema: 'TEMA I',
          seccion: 'Desafíos y ética',
          text: 'La responsabilidad social frente a la IA implica considerar:',
          opts: [
            'La eliminación total de la supervisión humana',
            'El reskilling de los trabajadores y diseñar tecnología que amplifique capacidades humanas',
            'Únicamente la reducción de costos empresariales',
            'El aumento de la brecha digital sin medidas correctivas',
          ],
          answer: 1,
        },

        // ── TEMA VI: Actualidad ──
        {
          id: 'ia43',
          tema: 'TEMA I',
          seccion: 'Actualidad',
          text: 'La Visión por Computadora permite que las máquinas:',
          opts: [
            '"Vean", por ejemplo mediante reconocimiento de objetos',
            '"Hablen", mediante chatbots y traducción',
            '"Actúen", mediante control autónomo',
            '"Escuchen", exclusivamente mediante reconocimiento de voz',
          ],
          answer: 0,
        },
        {
          id: 'ia44',
          tema: 'TEMA I',
          seccion: 'Actualidad',
          text: 'El Procesamiento de Lenguaje Natural (PLN) permite que las máquinas:',
          opts: [
            '"Vean": reconocimiento de objetos',
            '"Calculen": operaciones matemáticas avanzadas',
            '"Hablen": chatbots, traducción y análisis de sentimientos',
            '"Actúen": automatización industrial',
          ],
          answer: 2,
        },
        {
          id: 'ia45',
          tema: 'TEMA I',
          seccion: 'Actualidad',
          text: 'Entre las competencias clave más allá del código para trabajar en IA se encuentran:',
          opts: [
            'Únicamente conocimientos de hardware',
            'Solo dominar Python avanzado',
            'Solo experiencia en marketing digital',
            'Estadística, Storytelling, Trabajo en equipo y Ética',
          ],
          answer: 3,
        },
        {
          id: 'ia46',
          tema: 'TEMA I',
          seccion: 'Actualidad',
          text: 'Un ejemplo de proyecto de portafolio en IA mencionado es:',
          opts: [
            'Un servidor web estático',
            'Una base de datos relacional compleja',
            'Un Clasificador de Spam usando NLP y clasificación',
            'Un sistema operativo desde cero',
          ],
          answer: 2,
        },
      ];
