// ── MATERIA: INTELIGENCIA ARTIFICIAL ──
// Generado a partir de "IA para Ingenieros: Primeros Pasos" (Ing. Brian Peñafiel Plata, UNIOR)
const IA_TEMAS = ['TODOS', 'TEMA I'];
const IA_SECCIONES = [
  'TODAS',
  '¿Qué es la IA?',
  '¿Cómo aprende la IA?',
  'Herramientas y lenguajes',
  'Proyecto primer modelo',
  'Desafíos y ética',
  'Actualidad',
];

const IA_QUESTIONS = [
  // ── ¿Qué es la IA? ──
  {
    id: 'ia1',
    tema: 'TEMA I',
    seccion: '¿Qué es la IA?',
    text: 'La Inteligencia Artificial diseña sistemas capaces de realizar tareas que requieren inteligencia humana, como:',
    opts: ['Diseñar, fabricar y vender', 'Compilar, ejecutar y depurar', 'Aprender, razonar y tomar decisiones', 'Almacenar, indexar y respaldar'],
    answer: 2,
  },
  {
    id: 'ia2',
    tema: 'TEMA I',
    seccion: '¿Qué es la IA?',
    text: 'La IA Estrecha se define como aquella:',
    opts: [
      'Con habilidades cognitivas humanas en cualquier contexto',
      'Capaz de superar ampliamente la inteligencia humana',
      'Que aún es un objetivo hipotético de investigación',
      'Diseñada para tareas específicas, como las recomendaciones de Netflix',
    ],
    answer: 3,
  },
  {
    id: 'ia3',
    tema: 'TEMA I',
    seccion: '¿Qué es la IA?',
    text: 'La IA General se caracteriza por ser:',
    opts: [
      'Hipotética, con habilidades cognitivas humanas en cualquier contexto, aún objetivo de investigación',
      'La IA que usamos a diario en aplicaciones como streaming',
      'Capaz de superar la inteligencia humana',
      'Un framework desarrollado por Google',
    ],
    answer: 0,
  },
  {
    id: 'ia4',
    tema: 'TEMA I',
    seccion: '¿Qué es la IA?',
    text: 'En la línea de tiempo de la IA, el año 1956 corresponde a:',
    opts: ['La crisis de financiación', 'Los primeros programas de ajedrez', 'El auge por Big Data y la nube', 'El nacimiento de la IA en Dartmouth'],
    answer: 3,
  },
  {
    id: 'ia5',
    tema: 'TEMA I',
    seccion: '¿Qué es la IA?',
    text: "La etapa de los 'Inviernos de la IA' se describe como:",
    opts: ['Crisis de financiación y expectativas', 'Primeros programas de ajedrez', 'Nacimiento de la IA en Dartmouth', 'Auge por Big Data y la nube'],
    answer: 0,
  },
  {
    id: 'ia6',
    tema: 'TEMA I',
    seccion: '¿Qué es la IA?',
    text: "En el ciclo de vida de un sistema de IA, después de 'Datos de Entrenamiento' y 'Algoritmos' se obtiene:",
    opts: ['Modelo Predictivo', 'Base de datos', 'Evaluación y Métricas', 'Despliegue y Retroalimentación'],
    answer: 0,
  },

  // ── ¿Cómo aprende la IA? ──
  {
    id: 'ia7',
    tema: 'TEMA I',
    seccion: '¿Cómo aprende la IA?',
    text: 'Los tres tipos principales de aprendizaje automático son:',
    opts: [
      'Supervisado, No Supervisado y por Refuerzo',
      'Rápido, Lento y Progresivo',
      'Manual, Automático y Semiautomático',
      'Lineal, No lineal y Cuántico',
    ],
    answer: 0,
  },
  {
    id: 'ia8',
    tema: 'TEMA I',
    seccion: '¿Cómo aprende la IA?',
    text: 'En el Aprendizaje Supervisado, el primer paso del proceso es:',
    opts: ['Validar y Probar', 'Seleccionar Algoritmo', 'Recolectar Datos', 'Ajustar Parámetros'],
    answer: 2,
  },
  {
    id: 'ia9',
    tema: 'TEMA I',
    seccion: '¿Cómo aprende la IA?',
    text: 'Un ejemplo típico de Aprendizaje No Supervisado es:',
    opts: [
      'Clasificación de imágenes de gatos y perros',
      'Entrenar a un perro con premios',
      'Agrupamiento (K-means) para segmentar clientes según su comportamiento de compra',
      'Predicción de precios de viviendas',
    ],
    answer: 2,
  },
  {
    id: 'ia10',
    tema: 'TEMA I',
    seccion: '¿Cómo aprende la IA?',
    text: 'El objetivo del Aprendizaje por Refuerzo es:',
    opts: [
      'Maximizar la recompensa acumulada a largo plazo',
      'Eliminar por completo el error de entrenamiento',
      'Minimizar la cantidad de datos utilizados',
      'Reducir el número de neuronas de la red',
    ],
    answer: 0,
  },
  {
    id: 'ia11',
    tema: 'TEMA I',
    seccion: '¿Cómo aprende la IA?',
    text: 'El proceso mediante el cual una red neuronal ajusta sus pesos a partir del error se llama:',
    opts: ['Codificación One-Hot', 'Propagación hacia adelante (Forward pass)', 'Propagación hacia atrás (Backpropagation)', 'Escalado de datos'],
    answer: 2,
  },

  // ── Herramientas y lenguajes ──
  {
    id: 'ia12',
    tema: 'TEMA I',
    seccion: 'Herramientas y lenguajes',
    text: 'Para empezar con Python en IA se recomienda instalar:',
    opts: ['WordPress', 'Anaconda', 'Photoshop', 'AutoCAD'],
    answer: 1,
  },
  {
    id: 'ia13',
    tema: 'TEMA I',
    seccion: 'Herramientas y lenguajes',
    text: 'NumPy es una librería que proporciona principalmente:',
    opts: ['Visualización de gráficos interactivos', 'Modelos de deep learning preentrenados', 'DataFrames para tablas de datos', 'Arrays eficientes y operaciones vectorizadas'],
    answer: 3,
  },
  {
    id: 'ia14',
    tema: 'TEMA I',
    seccion: 'Herramientas y lenguajes',
    text: 'pandas se utiliza principalmente para:',
    opts: ['Manipular tablas de datos mediante DataFrames', 'Crear interfaces web', 'Entrenar redes neuronales profundas', 'Gestionar servidores en la nube'],
    answer: 0,
  },
  {
    id: 'ia15',
    tema: 'TEMA I',
    seccion: 'Herramientas y lenguajes',
    text: 'Scikit-learn permite entrenar y evaluar modelos de:',
    opts: ['Clasificación, regresión y clustering', 'Procesamiento de video en tiempo real', 'Bases de datos distribuidas', 'Únicamente redes neuronales convolucionales'],
    answer: 0,
  },
  {
    id: 'ia16',
    tema: 'TEMA I',
    seccion: 'Herramientas y lenguajes',
    text: 'TensorFlow es un framework desarrollado por:',
    opts: ['Apple', 'Google', 'Amazon', 'Microsoft'],
    answer: 1,
  },

  // ── Proyecto primer modelo ──
  {
    id: 'ia17',
    tema: 'TEMA I',
    seccion: 'Proyecto primer modelo',
    text: 'El primer paso en la planificación de un proyecto de IA es:',
    opts: ['Recopilar Datos', 'Entrenar el modelo', 'Preparar Datos', 'Definir Problema'],
    answer: 3,
  },
  {
    id: 'ia18',
    tema: 'TEMA I',
    seccion: 'Proyecto primer modelo',
    text: 'La función de pandas que muestra estadísticas descriptivas es:',
    opts: ['df.describe()', 'df.hist()', 'df.info()', 'df.corr()'],
    answer: 0,
  },
  {
    id: 'ia19',
    tema: 'TEMA I',
    seccion: 'Proyecto primer modelo',
    text: 'La técnica utilizada para transformar variables categóricas en numéricas se llama:',
    opts: ['Backpropagation', 'One-Hot Encoding', 'train_test_split', 'StandardScaler'],
    answer: 1,
  },
  {
    id: 'ia20',
    tema: 'TEMA I',
    seccion: 'Proyecto primer modelo',
    text: 'La función train_test_split se utiliza para:',
    opts: [
      'Entrenar el modelo final',
      'Codificar variables categóricas',
      'Separar los datos en conjuntos de entrenamiento (80%) y prueba (20%)',
      'Visualizar la distribución de variables',
    ],
    answer: 2,
  },
  {
    id: 'ia21',
    tema: 'TEMA I',
    seccion: 'Proyecto primer modelo',
    text: 'El coeficiente R² (coeficiente de determinación) indica:',
    opts: [
      'El número de capas de una red neuronal',
      'Qué proporción de la varianza en los datos es explicada por el modelo',
      'La velocidad de entrenamiento del modelo',
      'El número total de datos del dataset',
    ],
    answer: 1,
  },

  // ── Desafíos y ética ──
  {
    id: 'ia22',
    tema: 'TEMA I',
    seccion: 'Desafíos y ética',
    text: 'El desafío del sesgo en IA ocurre porque los modelos:',
    opts: [
      'Nunca utilizan datos reales',
      'Aprenden de datos históricos que pueden reflejar discriminaciones',
      'No requieren de datos para entrenarse',
      'Solo funcionan con datos sintéticos',
    ],
    answer: 1,
  },
  {
    id: 'ia23',
    tema: 'TEMA I',
    seccion: 'Desafíos y ética',
    text: 'El Federated Learning es una solución de privacidad que permite:',
    opts: [
      'Aumentar la exposición de datos sensibles',
      'Entrenar modelos sin centralizar los datos',
      'Eliminar la necesidad de entrenar modelos',
      'Centralizar todos los datos en un único servidor',
    ],
    answer: 1,
  },
  {
    id: 'ia24',
    tema: 'TEMA I',
    seccion: 'Desafíos y ética',
    text: 'Herramientas como SHAP y LIME se utilizan para:',
    opts: [
      'Entrenar redes neuronales más rápido',
      'Recolectar datos de sensores IoT',
      'Codificar variables categóricas',
      'Generar explicaciones locales sobre qué variables influyeron en una predicción',
    ],
    answer: 3,
  },

  // ── Actualidad ──
  {
    id: 'ia25',
    tema: 'TEMA I',
    seccion: 'Actualidad',
    text: 'El Procesamiento de Lenguaje Natural (PLN) permite que las máquinas:',
    opts: ['"Hablen": chatbots, traducción y análisis de sentimientos', '"Vean": reconocimiento de objetos', '"Actúen": automatización industrial', '"Calculen": operaciones matemáticas avanzadas'],
    answer: 0,
  },
];