// ── MATERIA: INTELIGENCIA ARTIFICIAL ──
// Generado a partir de "IA para Ingenieros: Primeros Pasos" (Ing. Brian Peñafiel Plata, UNIOR)
const IA_TEMAS = ['TODOS', 'TEMA I'];
const IA_SECCIONES = [
  'TODAS',
  '¿Qué es la IA?',
  'Aprendizaje Supervisado',
  'Aprendizaje No Supervisado',
  'Aprendizaje por Refuerzo',
  'Redes Neuronales',
  'Herramientas y Lenguajes',
  'Proyecto y Preprocesamiento',
  'Ética y Responsabilidad',
];

const IA_QUESTIONS = [
  // ── ¿Qué es la IA? ──
  {
    id: 'ia1',
    tema: 'TEMA I',
    seccion: '¿Qué es la IA?',
    text: '¿Cuál es IA Estrecha?',
    opts: [
      'Un sistema que realiza múltiples tareas distintas simultáneamente',
      'Un algoritmo que SOLO reconoce rostros en tu teléfono y nada más (no puede traducir idiomas, ni jugar ajedrez)',
      'Un sistema capaz de resolver cualquier problema cognitivo humano',
      'Una máquina que puede aprender nuevas tareas sin reentrenamiento',
    ],
    answer: 1,
  },
  {
    id: 'ia2',
    tema: 'TEMA I',
    seccion: '¿Qué es la IA?',
    text: '¿Cuál es la diferencia entre IA General e IA Estrecha?',
    opts: [
      'IA General es más rápida en procesamiento',
      'IA General podría resolver CUALQUIER tarea cognitiva humana (como un humano), mientras que IA Estrecha solo resuelve una tarea específica (ej: Google Translate solo traduce, Siri solo escucha comandos)',
      'IA General requiere menos datos de entrenamiento',
      'IA General funciona sin necesidad de datos',
    ],
    answer: 1,
  },
  {
    id: 'ia3',
    tema: 'TEMA I',
    seccion: '¿Qué es la IA?',
    text: '¿En qué año se formalizó el campo de la IA en la conferencia de Dartmouth?',
    opts: ['1943', '1956', '1974', '1997'],
    answer: 1,
  },
  {
    id: 'ia4',
    tema: 'TEMA I',
    seccion: '¿Qué es la IA?',
    text: '¿Qué caracterizó las "Épocas Doradas" de la IA?',
    opts: [
      'La creación de máquinas superinteligentes',
      'Desarrollo de programas de ajedrez y gran optimismo (ej: pensaron que en 20 años tendríamos asistentes virtuales perfectos)',
      'La prohibición de investigar IA',
      'Colapso de la inversión en tecnología',
    ],
    answer: 1,
  },
  {
    id: 'ia5',
    tema: 'TEMA I',
    seccion: '¿Qué es la IA?',
    text: '¿Qué fueron los "Inviernos de la IA"?',
    opts: [
      'Períodos con temperaturas bajas extremas',
      'Períodos de crisis financiera y promesas no cumplidas (ej: los asistentes virtuales "perfectos" no llegaron)',
      'Épocas donde la IA se volvió demasiado peligrosa',
      'Años donde los científicos dejaron completamente el campo',
    ],
    answer: 1,
  },
  {
    id: 'ia6',
    tema: 'TEMA I',
    seccion: '¿Qué es la IA?',
    text: '¿Cuál fue el principal factor en el resurgimiento de la IA después de 2010?',
    opts: [
      'Invención de nuevos lenguajes de programación',
      'Disponibilidad masiva de datos y poder computacional en la nube (ej: Netflix viendo tus películas, YouTube viendo tus búsquedas)',
      'Regulaciones gubernamentales',
      'Mejoras en infraestructura de cables',
    ],
    answer: 1,
  },
  {
    id: 'ia7',
    tema: 'TEMA I',
    seccion: '¿Qué es la IA?',
    text: '¿Cuál es la definición de Inteligencia Artificial?',
    opts: [
      'Un robot que habla como humano',
      'La rama de la informática que diseña sistemas capaces de realizar tareas que requieren inteligencia humana',
      'Un programa que gana competencias',
      'Cualquier máquina automática',
    ],
    answer: 1,
  },
  {
    id: 'ia8',
    tema: 'TEMA I',
    seccion: '¿Qué es la IA?',
    text: '¿Qué significa que un modelo de IA "aprenda"?',
    opts: [
      'Que descargue información de internet',
      'Que recuerde conversaciones anteriores',
      'Que ajuste sus parámetros internos basándose en datos para mejorar (ej: TikTok ve que ves 10 segundos de baile y 2 de noticias, ajusta para mostrarte más baile)',
      'Que desarrolle conciencia',
    ],
    answer: 2,
  },

  // ── Aprendizaje Supervisado ──
  {
    id: 'ia9',
    tema: 'TEMA I',
    seccion: 'Aprendizaje Supervisado',
    text: '¿Cuál es un ejemplo de Aprendizaje Supervisado?',
    opts: [
      'YouTube agrupa videos en géneros que descubre automáticamente',
      'Tu teléfono aprende a reconocer tu cara usando miles de fotos tuyas etiquetadas como "tu cara" o "no tu cara"',
      'Netflix descubre qué tipo de películas te gustan sin que las etiquetes',
      'Spotify te muestra canciones similares a las que escuchas',
    ],
    answer: 1,
  },
  {
    id: 'ia10',
    tema: 'TEMA I',
    seccion: 'Aprendizaje Supervisado',
    text: '¿Qué caracteriza al Aprendizaje Supervisado?',
    opts: [
      'El modelo aprende completamente solo sin ayuda',
      'Los datos incluyen entrada + la respuesta correcta (ej: foto de tu perro + "es tu perro", foto ajena + "no es tu perro")',
      'Solo funciona con redes profundas',
      'El modelo puede aprender mientras está en uso',
    ],
    answer: 1,
  },
  {
    id: 'ia11',
    tema: 'TEMA I',
    seccion: 'Aprendizaje Supervisado',
    text: '¿Cuál es una tarea de Aprendizaje Supervisado?',
    opts: [
      'Instagram agrupa tus fotos en álbumes automáticamente sin decirle cuáles son vacaciones',
      'Google Photos aprende a identificar si hay gatos en tus fotos usando millones de fotos etiquetadas como "gato" o "no gato"',
      'TikTok te muestra videos similares a los que viste',
      'Spotify descubre patrones en lo que escuchas',
    ],
    answer: 1,
  },

  // ── Aprendizaje No Supervisado ──
  {
    id: 'ia12',
    tema: 'TEMA I',
    seccion: 'Aprendizaje No Supervisado',
    text: '¿Cuál es un ejemplo de Aprendizaje No Supervisado?',
    opts: [
      'Tu corrector de WhatsApp usa palabras etiquetadas como "correctas" e "incorrectas"',
      'Instagram agrupa automáticamente a usuarios: algunos solo ven moda, otros solo viajes, otros solo comida, sin que Instagram te diga qué categoría eres',
      'Google Translate usa millones de frases etiquetadas en pares de idiomas',
      'Netflix usa películas etiquetadas por género',
    ],
    answer: 1,
  },
  {
    id: 'ia13',
    tema: 'TEMA I',
    seccion: 'Aprendizaje No Supervisado',
    text: '¿Cuál es el objetivo del Aprendizaje No Supervisado?',
    opts: [
      'Etiquetar datos manualmente',
      'Descubrir patrones ocultos sin que nadie te diga qué buscar (ej: Gmail ve que recibes correos de tu mamá, trabajo, compras, agrupa automáticamente)',
      'Entrenar rápidamente',
      'Eliminar datos',
    ],
    answer: 1,
  },
  {
    id: 'ia14',
    tema: 'TEMA I',
    seccion: 'Aprendizaje No Supervisado',
    text: '¿Cuál es una característica del Aprendizaje No Supervisado?',
    opts: [
      'Requiere etiquetas claras como "correcto/incorrecto"',
      'El modelo descubre grupos por sí solo sin categorías previas (ej: YouTube agrupa a usuarios en "ven tutoriales", "ven música", "ven comedia" automáticamente)',
      'Solo predice números',
      'Necesita validación humana constante',
    ],
    answer: 1,
  },

  // ── Aprendizaje por Refuerzo ──
  {
    id: 'ia15',
    tema: 'TEMA I',
    seccion: 'Aprendizaje por Refuerzo',
    text: '¿Cuál es un ejemplo de Aprendizaje por Refuerzo?',
    opts: [
      'Clasificar tus correos como spam usando correos etiquetados previamente',
      'Google Photos agrupa tus fotos en álbumes automáticamente',
      'Un videojuego donde un personaje aprende: cada vez que choca con una pared pierde vida, cada vez que recoge monedas gana puntos, mejora su camino',
      'Spotify te recomienda canciones similares',
    ],
    answer: 2,
  },
  {
    id: 'ia16',
    tema: 'TEMA I',
    seccion: 'Aprendizaje por Refuerzo',
    text: '¿Cuál es el principio del Aprendizaje por Refuerzo?',
    opts: [
      'Recibir etiquetas correctas para cada ejemplo',
      'El agente intenta acciones, recibe retroalimentación (recompensa o penalización) y mejora (ej: un perro hace un truco → recibe galleta → repite el truco)',
      'Descubrir patrones sin intervención',
      'Memorizar todas las experiencias',
    ],
    answer: 1,
  },
  {
    id: 'ia17',
    tema: 'TEMA I',
    seccion: 'Aprendizaje por Refuerzo',
    text: '¿Qué distingue al Aprendizaje por Refuerzo?',
    opts: [
      'Requiere datos completamente etiquetados',
      'El agente aprende haciendo: intenta acción → obtiene puntos/penalización → ajusta estrategia (ej: un robot aspirador choca con pared = no funciona bien, limpia todo bien = funciona bien, aprende mejor ruta)',
      'No funciona en robots reales',
      'Solo para videojuegos',
    ],
    answer: 1,
  },

  // ── Redes Neuronales ──
  {
    id: 'ia18',
    tema: 'TEMA I',
    seccion: 'Redes Neuronales',
    text: '¿Qué es la "propagación hacia atrás" (backpropagation)?',
    opts: [
      'Cuando una red neuronal olvida lo aprendido',
      'Un algoritmo que calcula: "este parámetro causó error grande, cambialo" (como cuando escribes un mensaje en WhatsApp mal escrito, ves el error, lo corriges)',
      'Conectar capas automáticamente',
      'Eliminar datos defectuosos',
    ],
    answer: 1,
  },
  {
    id: 'ia19',
    tema: 'TEMA I',
    seccion: 'Redes Neuronales',
    text: '¿Cuál es el propósito del "Forward Pass"?',
    opts: [
      'Eliminar capas innecesarias',
      'Pasar datos hacia adelante a través de la red para obtener una predicción (ej: tu foto entra al Face ID → pasa por capas → sale "es tu cara" o "no es tu cara")',
      'Corregir errores del paso anterior',
      'Aumentar velocidad de procesamiento',
    ],
    answer: 1,
  },
  {
    id: 'ia20',
    tema: 'TEMA I',
    seccion: 'Redes Neuronales',
    text: '¿Por qué importan las funciones de activación no lineales?',
    opts: [
      'Para hacer código más legible',
      'Para reducir parámetros del modelo',
      'Permiten que la red aprenda relaciones complejas que operaciones simples no pueden (ej: sin ellas, un filtro de fotos solo oscurece uniformemente; con ellas, detecta si estás sonriendo)',
      'Para conectar capas automáticamente',
    ],
    answer: 2,
  },
  {
    id: 'ia21',
    tema: 'TEMA I',
    seccion: 'Redes Neuronales',
    text: '¿Cuál es la diferencia entre red neuronal simple y Deep Learning?',
    opts: [
      'Deep Learning es más lento',
      'Deep Learning usa muchas capas que reconocen detalles cada vez más complejos (ej: capa 1 ve píxeles, capa 5 ve ojos y boca, capa 10 ve rostro y emoción)',
      'Deep Learning solo funciona con imágenes',
      'Son exactamente iguales',
    ],
    answer: 1,
  },

  // ── Herramientas y Lenguajes ──
  {
    id: 'ia22',
    tema: 'TEMA I',
    seccion: 'Herramientas y Lenguajes',
    text: '¿Por qué Python domina en IA?',
    opts: [
      'Es el lenguaje más antiguo',
      'Tiene sintaxis simple y herramientas listas para IA (ej: en Python escribes 10 líneas para que tu teléfono reconozca rostros, en C++ escribes 500)',
      'Es obligatorio usar Python',
      'Consume menos energía eléctrica',
    ],
    answer: 1,
  },
  {
    id: 'ia23',
    tema: 'TEMA I',
    seccion: 'Herramientas y Lenguajes',
    text: '¿Cuál es el propósito de Jupyter Notebook?',
    opts: [
      'Reemplazar Python como lenguaje',
      'Escribir código en pequeñas celdas y ver resultados al instante (ej: ajustas cómo el filtro de Instagram reconoce rostros, lo ejecutas, ves si funciona mejor, cambias de nuevo)',
      'Compilar código automáticamente a máquina',
      'Crear videos tutoriales',
    ],
    answer: 1,
  },
  {
    id: 'ia24',
    tema: 'TEMA I',
    seccion: 'Herramientas y Lenguajes',
    text: '¿Qué hace NumPy eficiente?',
    opts: [
      'Procesa solo texto y lenguaje',
      'Realiza cálculos matemáticos muy rápido con vectores (ej: calcular recomendaciones para 1 millón de usuarios en 1 segundo)',
      'Funciona solo con números enteros',
      'Gestiona imágenes JPG específicamente',
    ],
    answer: 1,
  },
  {
    id: 'ia25',
    tema: 'TEMA I',
    seccion: 'Herramientas y Lenguajes',
    text: '¿Cuál es la diferencia entre NumPy y pandas?',
    opts: [
      'NumPy es siempre más rápido',
      'NumPy hace cálculos matemáticos; pandas organiza datos como Excel (ej: pandas tiene columnas con nombres como "edad", "ciudad", "compras")',
      'Pandas es subconjunto de NumPy',
      'Son iguales',
    ],
    answer: 1,
  },
  {
    id: 'ia26',
    tema: 'TEMA I',
    seccion: 'Herramientas y Lenguajes',
    text: '¿Cuál es ventaja de Scikit-learn?',
    opts: [
      'Entrena deep learning automáticamente',
      'Puedes entrenar modelos complejos en pocas líneas sin código complicado (ej: predecir si alguien comprará en tu tienda en 3 líneas de código)',
      'Más potente que TensorFlow en todos los aspectos',
      'Solo funciona en la nube',
    ],
    answer: 1,
  },

  // ── Proyecto y Preprocesamiento ──
  {
    id: 'ia27',
    tema: 'TEMA I',
    seccion: 'Proyecto y Preprocesamiento',
    text: '¿Cuál es el primer paso en un proyecto IA?',
    opts: [
      'Seleccionar modelo de Deep Learning',
      'Definir claramente qué quieres predecir y cómo sabrás si funciona (ej: "predecir si un cliente volverá a comprar" → métrica: 90% de precisión)',
      'Recolectar datos máximo posible',
      'Publicar resultados',
    ],
    answer: 1,
  },
  {
    id: 'ia28',
    tema: 'TEMA I',
    seccion: 'Proyecto y Preprocesamiento',
    text: '¿Cuál es el propósito de "One-Hot Encoding"?',
    opts: [
      'Reducir tamaño de archivo',
      'Convertir categorías en números que el modelo entienda (ej: ciudad "Madrid" → [1,0,0], "Barcelona" → [0,1,0], "Valencia" → [0,0,1])',
      'Optimizar internet',
      'Eliminar datos faltantes',
    ],
    answer: 1,
  },
  {
    id: 'ia29',
    tema: 'TEMA I',
    seccion: 'Proyecto y Preprocesamiento',
    text: '¿Por qué normalizar variables numéricas?',
    opts: [
      'Para código legible',
      'Para que todas tengan peso similar (ej: si tienes edad (0-100) e ingresos (0-1,000,000), ingresos no debería dominar solo por ser número grande; Instagram hace esto para tus búsquedas)',
      'Requisito legal',
      'Reducir tiempo de entrenamiento',
    ],
    answer: 1,
  },
  {
    id: 'ia30',
    tema: 'TEMA I',
    seccion: 'Proyecto y Preprocesamiento',
    text: '¿Cuál es la división típica de datos entrenamiento/prueba?',
    opts: [
      '99% - 1%',
      '80% - 20% (ej: de 100 fotos de tu rostro para Face ID, entrenas con 80, pruebas con 20 que el modelo nunca vio)',
      '50% - 50%',
      '95% - 5%',
    ],
    answer: 1,
  },
  {
    id: 'ia31',
    tema: 'TEMA I',
    seccion: 'Proyecto y Preprocesamiento',
    text: '¿Qué mide el coeficiente R²?',
    opts: [
      'Número de parámetros',
      'Qué tan bien tu modelo explica los datos, de 0 a 1 (ej: R²=0.85 significa que explica el 85% de por qué algunos usuarios ven más TikTok que otros)',
      'La velocidad del modelo',
      'Cantidad de datos',
    ],
    answer: 1,
  },
  {
    id: 'ia32',
    tema: 'TEMA I',
    seccion: 'Proyecto y Preprocesamiento',
    text: '¿Cuál es el orden correcto en Machine Learning?',
    opts: [
      'Evaluar → Entrenar → Dividir → Cargar',
      'Cargar datos → Dividir en 80/20 → Entrenar modelo → Predecir → Evaluar resultados (ej: como usar WhatsApp: descargar → configurar → usar → revisar si funciona)',
      'Predecir → Entrenar → Dividir',
      'Entrenar → Predecir → Dividir',
    ],
    answer: 1,
  },

  // ── Ética y Responsabilidad ──
  {
    id: 'ia33',
    tema: 'TEMA I',
    seccion: 'Ética y Responsabilidad',
    text: '¿Qué es el sesgo en IA?',
    opts: [
      'Un parámetro que mejora precisión',
      'Cuando el modelo aprende discriminaciones del pasado y las perpetúa (ej: un filtro de búsqueda que muestra menos a ciertas personas porque históricamente se buscaba más a otras)',
      'Un método para optimizar rápido',
      'Un nombre técnico',
    ],
    answer: 1,
  },
  {
    id: 'ia34',
    tema: 'TEMA I',
    seccion: 'Ética y Responsabilidad',
    text: '¿Cuál es un ejemplo de sesgo en IA?',
    opts: [
      'Algoritmo lento',
      'Un reconocedor facial que falla más en rostros oscuros porque fue entrenado mayormente con rostros claros (ej: el iPhone Face ID falla más con gente de piel oscura)',
      'Precisión muy alta',
      'Modelo que es rápido',
    ],
    answer: 1,
  },
  {
    id: 'ia35',
    tema: 'TEMA I',
    seccion: 'Ética y Responsabilidad',
    text: '¿Qué es Federated Learning?',
    opts: [
      'Centralizar todos los datos en un servidor',
      'Entrenar modelos en los dispositivos del usuario sin enviar datos personales a servidores (ej: tu teléfono aprende tu forma de escribir sin mandar tus mensajes a Google)',
      'Dividir trabajo entre departamentos',
      'Hacer todos los modelos iguales',
    ],
    answer: 1,
  },
];
