      const LEGISLACION_TEMAS = ['TODOS', 'TEMA I', 'TEMA II', 'TEMA III', 'TEMA IV', 'TEMA V'];

      const ALL_QUESTIONS = [
        // ── PARCIAL (7 preguntas únicas) ──
        {
          id: 'p1',
          tema: 'TEMA V',
          text: 'Los derechos de las personas y la informática, conocidos como:',
          opts: ['derechos informáticos', 'derecho privado', 'Derecho Personal', 'derechos digitales'],
          answer: 3,
        },
        {
          id: 'p2',
          tema: 'TEMA V',
          text: 'Los Derechos Humanos no pueden ser:',
          opts: ['Cedidos', 'Imprescriptibles', 'Esporádicos', 'Universales'],
          answer: 0,
        },
        {
          id: 'p4',
          tema: 'TEMA V',
          text: 'De acuerdo a la jurisprudencia se toma en cuenta que el derecho a la privacidad tiene dos sentidos:',
          opts: [
            'El primero conocido como el sentido natural y el segundo como el sentido negativo.',
            'El primero conocido como el sentido positivo y el segundo como el sentido universal.',
            'El primero conocido como el sentido positivo y el segundo como el sentido negativo.',
            'El primero conocido como el sentido natural y el segundo como el sentido positivo.',
          ],
          answer: 2,
        },
        {
          id: 'p5',
          tema: 'TEMA V',
          text: 'Para los países que siguen las estructuras básicas del sistema continental romanista, la Ley es considerada como una:',
          opts: ['Costumbre', 'Fuente', 'Norma', 'Jurisprudencia'],
          answer: 1,
        },
        {
          id: 'p6',
          tema: 'TEMA V',
          text: 'La doctrina para Manuel Ossorio dice:',
          opts: [
            'Conjunto de normas de los tratadistas y estudiosos de las leyes que explican y fijan el sentido de las leyes o sugieren soluciones para cuestiones aún no legisladas.',
            'Conjunto de Leyes y opiniones de los tratadistas y estudiosos que explican y fijan el sentido y sugieren soluciones para cuestiones aún no legisladas.',
            'Conjunto de tesis y opiniones de los tratadistas y estudiosos del derecho que explican y fijan el sentido de las leyes o sugieren soluciones para cuestiones aún no legisladas.',
            'Conjunto de normas y leyes de los tratadistas y estudiosos del derecho que explican y fijan el sentido positivo del derecho.',
          ],
          answer: 2,
        },
        {
          id: 'p7',
          tema: 'TEMA V',
          text: 'El Dr. Marcelo Fernández dice que en el Derecho Informático existen dos tipos de fuentes que son:',
          opts: [
            'Fuentes Interdisciplinarias y Fuentes Transdisciplinarias',
            'Fuentes la costumbre y Fuentes Jurisprudencia',
            'Fuentes Primarias y Fuentes Secundarias',
            'Fuentes Nacionales y Fuentes Internacionales',
          ],
          answer: 0,
        },
        {
          id: 'p10',
          tema: 'TEMA I',
          text: 'Se podría definir el delito informático como:',
          opts: [
            'toda acción (acción u omisión) no culpable realizada por un ser humano, que cause un perjuicio a personas sin que necesariamente se beneficie el autor',
            'toda acción (acción u omisión) culpable realizada por un ser humano, que cause un perjuicio a personas sin que necesariamente se beneficie el autor',
            'toda acción (acción u omisión) culpable realizada por un delincuente, que cause o no un perjuicio a la sociedad sin que necesariamente se beneficie el autor',
            'toda acción (acción u omisión) realizada por un ciudadano, que cause un perjuicio a personas sin que necesariamente se beneficie el autor',
          ],
          answer: 0,
        },

        // ── EXAMEN 50 PREGUNTAS ──
        {
          id: 'e1',
          tema: 'TEMA I',
          text: 'El Artículo 363 ter del Código Penal boliviano tipifica delitos relacionados con:',
          opts: [
            'La manipulación informática para beneficio económico indebido',
            'La alteración, acceso y uso indebido de datos informáticos',
            'El fraude electrónico y la estafa en redes sociales',
            'La interceptación ilegal de comunicaciones privadas',
          ],
          answer: 1,
        },
        {
          id: 'e2',
          tema: 'TEMA I',
          text: "La 'alteración de datos' según el Art. 363 ter implica:",
          opts: [
            'La obtención no autorizada de información de un sistema',
            'El acceso sin permiso a sistemas informáticos de terceros',
            'La modificación, supresión o deterioro intencional de datos informáticos',
            'La publicación de datos personales sin consentimiento',
          ],
          answer: 2,
        },
        {
          id: 'e3',
          tema: 'TEMA I',
          text: "El 'acceso indebido a datos' consiste en:",
          opts: [
            'La modificación de registros en bases de datos gubernamentales',
            'La obtención, copia o sustracción no autorizada de información contenida en un sistema',
            'La instalación de software malicioso en equipos ajenos',
            'La interceptación de comunicaciones en redes públicas',
          ],
          answer: 1,
        },
        {
          id: 'e4',
          tema: 'TEMA I',
          text: "Una 'violación de datos' o brecha de datos ocurre cuando datos sensibles son copiados, transmitidos o utilizados por:",
          opts: [
            'Un funcionario público sin orden judicial',
            'Un proveedor de servicios con contrato vencido',
            'Una persona no autorizada',
            'Un tercero con acceso parcial al sistema',
          ],
          answer: 2,
        },
        {
          id: 'e5',
          tema: 'TEMA I',
          text: 'La doctrina jurídica en protección de datos informáticos enfatiza tres principios: confidencialidad, integridad y:',
          opts: ['Universalidad', 'Proporcionalidad', 'Disponibilidad', 'Territorialidad'],
          answer: 2,
        },
        {
          id: 'e6',
          tema: 'TEMA I',
          text: "Un ejemplo claro de 'acceso indebido a datos' es:",
          opts: [
            'Modificar calificaciones en un sistema académico',
            'Descargar ilegalmente bases de datos con números de tarjetas de crédito',
            'Borrar registros contables de una empresa',
            'Instalar un programa espía en un dispositivo ajeno',
          ],
          answer: 1,
        },
        {
          id: 'e7',
          tema: 'TEMA I',
          text: 'Los bienes jurídicos que el Art. 363 ter busca proteger son:',
          opts: [
            'El patrimonio económico y la propiedad intelectual',
            'La confidencialidad, integridad y disponibilidad de la información digital',
            'La libertad de expresión y el acceso libre a la información',
            'La seguridad nacional y los sistemas de defensa estatal',
          ],
          answer: 1,
        },
        {
          id: 'e8',
          tema: 'TEMA I',
          text: 'Según la doctrina boliviana, el delito del Art. 363 ter se diferencia del Art. 363 bis porque:',
          opts: [
            'El 363 ter requiere beneficio económico y el 363 bis no',
            'El 363 bis sanciona la manipulación informática y el 363 ter el acceso, alteración y uso indebido de datos',
            'El 363 ter aplica solo a personas jurídicas y el 363 bis a personas naturales',
            'Ambos son idénticos, solo difieren en la pena aplicable',
          ],
          answer: 1,
        },
        {
          id: 'e9',
          tema: 'TEMA I',
          text: "La 'integridad' como principio de protección de datos informáticos se refiere a:",
          opts: [
            'La accesibilidad de los datos cuando se los necesita',
            'La protección contra accesos no autorizados externos',
            'La precisión e inalterabilidad de los datos',
            'La confidencialidad frente a terceros no autorizados',
          ],
          answer: 2,
        },
        {
          id: 'e10',
          tema: 'TEMA I',
          text: 'Las consecuencias de una violación de datos pueden incluir:',
          opts: [
            'Únicamente perjuicios económicos al titular de los datos',
            'Solo daño a la reputación pública de empresas involucradas',
            'Perjuicios económicos, usurpación de identidad o exposición pública de información confidencial',
            'Sanciones administrativas exclusivamente para el proveedor del sistema',
          ],
          answer: 2,
        },
        {
          id: 'e11',
          tema: 'TEMA II',
          text: 'El Artículo 363 bis del Código Penal (Manipulación informática) sanciona con:',
          opts: [
            '6 meses a 3 años a quien altere datos con fines de engaño',
            '1 a 5 años de reclusión a quien manipule datos para obtener beneficio indebido',
            'Multa equivalente al daño causado más 2 años de reclusión',
            '2 a 8 años a quien acceda ilegalmente a sistemas financieros',
          ],
          answer: 1,
        },
        {
          id: 'e12',
          tema: 'TEMA II',
          text: 'El delito informático más reportado en Bolivia según estadísticas 2024-2026 es:',
          opts: [
            'Robo de identidad y venta de datos en la Dark Web',
            'Fraude informático y estafas mediante phishing, ingeniería social y QR engañosos',
            'Deepfakes y fake news con inteligencia artificial',
            'Manipulación de sistemas municipales para evasión de impuestos',
          ],
          answer: 1,
        },
        {
          id: 'e13',
          tema: 'TEMA II',
          text: 'El grupo más propenso a sufrir fraudes y acoso digital en Bolivia es:',
          opts: [
            'Personas mayores de 50 años con cuentas bancarias activas',
            'Niños menores de 12 años con acceso a videojuegos en línea',
            'Jóvenes de 16 a 35 años, siendo las mujeres el grupo más afectado',
            'Adultos entre 36 y 50 años con acceso a banca digital',
          ],
          answer: 2,
        },
        {
          id: 'e14',
          tema: 'TEMA II',
          text: "El 'grooming' en el contexto de delitos informáticos en Bolivia se refiere a:",
          opts: [
            'El robo de identidad digital de personas adultas en redes sociales',
            'El acoso e incremento de violencia sexual a menores en redes sociales',
            'La distribución de malware a través de mensajes de correo electrónico',
            'La suplantación de identidad de funcionarios para obtener datos confidenciales',
          ],
          answer: 1,
        },
        {
          id: 'e15',
          tema: 'TEMA II',
          text: "Los 'deepfakes' como delito informático consisten en:",
          opts: [
            'La clonación de tarjetas bancarias mediante dispositivos físicos',
            'El acceso no autorizado a cámaras de vigilancia privadas',
            'El uso de inteligencia artificial para suplantar figuras públicas y promover engaños',
            'La creación de perfiles falsos en redes sociales para estafar',
          ],
          answer: 2,
        },
        {
          id: 'e16',
          tema: 'TEMA II',
          text: 'Un desafío principal en la persecución de delitos informáticos en Bolivia es:',
          opts: [
            'La falta de denuncias porque los delitos son considerados menores',
            'La alta impunidad por falta de pruebas o anonimato de los autores, y dificultad de jurisdicción cuando los servidores están en el extranjero',
            'La inexistencia de tipos penales específicos en el Código Penal',
            'La oposición de empresas tecnológicas a colaborar con la justicia boliviana',
          ],
          answer: 1,
        },
        {
          id: 'e17',
          tema: 'TEMA II',
          text: 'La Ley 164 de Telecomunicaciones junto al Art. 363 ter del Código Penal forman parte del marco normativo para:',
          opts: [
            'Regular el comercio electrónico y la firma digital en Bolivia',
            'Sancionar delitos contra la integridad sexual de menores en entornos digitales',
            'Proteger sistemas informáticos y datos digitales de accesos no autorizados',
            'Establecer derechos de autor sobre software de desarrollo nacional',
          ],
          answer: 2,
        },
        {
          id: 'e18',
          tema: 'TEMA II',
          text: 'El Código Niño, Niña y Adolescente en Bolivia, en relación al delito informático, regula específicamente:',
          opts: [
            'Las penas por manipulación de sistemas electorales con participación de menores',
            'El acoso cibernético (cyberbullying) y delitos de contacto sexual con menores en entornos digitales',
            'El acceso a internet de menores y la responsabilidad de los proveedores de servicio',
            'La propiedad intelectual de contenidos creados por menores de edad en plataformas digitales',
          ],
          answer: 1,
        },
        {
          id: 'e19',
          tema: 'TEMA II',
          text: '¿Por qué la Constitución Política del Estado (art. 21) es base de la legislación informática boliviana?',
          opts: [
            'Porque regula expresamente el uso de datos personales en plataformas digitales',
            'Porque establece el habeas data como garantía autónoma de aplicación inmediata',
            'Porque protege la privacidad e intimidad personal y familiar, fundamento constitucional de la protección de datos',
            'Porque prohíbe toda forma de vigilancia electrónica por parte de entidades estatales',
          ],
          answer: 2,
        },
        {
          id: 'e20',
          tema: 'TEMA II',
          text: 'El Ministerio Público de Bolivia ha registrado incremento en denuncias relacionadas con:',
          opts: [
            'Infracciones de derechos de autor en plataformas de streaming',
            'Estafa, acceso indebido a sistemas, alteración y acceso indebido de datos',
            'Violaciones de secreto profesional a través de medios digitales',
            'Uso no autorizado de redes Wi-Fi públicas en centros urbanos',
          ],
          answer: 1,
        },
        {
          id: 'e21',
          tema: 'TEMA III',
          text: 'La Ley N° 26.388 de Argentina (2008) es relevante en legislación comparada porque:',
          opts: [
            'Fue la primera ley latinoamericana exclusivamente sobre pornografía infantil digital',
            'Es la base normativa más consolidada de la región, con aplicación judicial desde hace más de 15 años',
            'Regula únicamente el acceso ilícito a sistemas bancarios y financieros',
            'Tipifica exclusivamente los delitos de grooming y acoso cibernético',
          ],
          answer: 1,
        },
        {
          id: 'e22',
          tema: 'TEMA III',
          text: 'El Artículo 153 bis del Código Penal Argentino (Ley 26.388) regula:',
          opts: [
            'La violación de correspondencia y comunicaciones electrónicas',
            'El daño informático y la destrucción intencional de sistemas',
            'El acceso ilícito a sistemas o datos informáticos de acceso restringido',
            'La apropiación de datos personales y robo de identidad digital',
          ],
          answer: 2,
        },
        {
          id: 'e23',
          tema: 'TEMA III',
          text: 'La sanción básica por acceso ilícito a sistemas informáticos en Argentina (Art. 153 bis CP) es:',
          opts: ['6 meses a 2 años de prisión', '15 días a 6 meses de prisión', '1 a 3 años de reclusión', 'Multa más 30 días de arresto'],
          answer: 1,
        },
        {
          id: 'e24',
          tema: 'TEMA III',
          text: 'En Argentina, si el acceso ilícito informático se produce contra un organismo público o servicio financiero, la pena se agrava a:',
          opts: ['6 meses a 2 años de prisión', '1 mes a 1 año de prisión', '2 a 4 años de reclusión', '3 a 6 años de prisión'],
          answer: 1,
        },
        {
          id: 'e25',
          tema: 'TEMA III',
          text: 'El Convenio de Budapest sobre Ciberdelincuencia es relevante en legislación comparada porque:',
          opts: [
            'Fue adoptado por Bolivia como norma de aplicación directa en 2015',
            'Argentina lo tomó como referencia para elaborar la Ley 26.388 de reforma al Código Penal',
            'Prohíbe a los países miembros tipificar el acceso sin daño como delito',
            'Establece penas mínimas uniformes de 5 años para todos los delitos informáticos',
          ],
          answer: 1,
        },
        {
          id: 'e26',
          tema: 'TEMA III',
          text: "Según la legislación argentina, la 'interceptación y violación de comunicaciones' (Arts. 153 y 155 CP) incluye:",
          opts: [
            'Solo el hackeo de cuentas de correo electrónico corporativas',
            'Capturar, leer, grabar o desviar mensajes de WhatsApp, correos, llamadas o cualquier transmisión privada sin permiso',
            'Exclusivamente la interceptación de comunicaciones telefónicas analógicas',
            'Únicamente el acceso no autorizado a archivos almacenados en la nube',
          ],
          answer: 1,
        },
        {
          id: 'e27',
          tema: 'TEMA III',
          text: 'La ventaja principal de la Ley 26.388 argentina frente a otras legislaciones regionales es que regula tanto:',
          opts: [
            'Delitos financieros digitales como delitos contra la propiedad intelectual',
            'Ataques contra sistemas/datos como fraudes, delitos contra la intimidad y delitos sexuales en entornos digitales',
            'Delitos cometidos por menores como delitos corporativos en el ciberespacio',
            'Delitos nacionales como delitos transfronterizos con extradición automática',
          ],
          answer: 1,
        },
        {
          id: 'e28',
          tema: 'TEMA III',
          text: "En la legislación comparada, la 'apropiación de datos' (Art. 157 bis CP argentino) se diferencia del 'acceso ilícito' porque:",
          opts: [
            'La apropiación requiere daño al sistema y el acceso no',
            'El acceso ilícito implica solo ingresar al sistema, mientras la apropiación implica tomar los datos con fines de uso o divulgación',
            'La apropiación de datos se aplica solo a personas jurídicas',
            'No existe diferencia práctica, ambos artículos sancionan la misma conducta',
          ],
          answer: 1,
        },
        {
          id: 'e29',
          tema: 'TEMA III',
          text: 'Un joven ingresa al sistema administrativo de una escuela privada y revisa listas de alumnos sin modificar ni llevarse información. Según la ley argentina, la sanción básica sería:',
          opts: [
            '30 días de arresto y multa',
            'Archivo de la causa por no producir daño',
            '3 meses de prisión (forma simple del Art. 153 bis)',
            '1 año de prisión por violación de privacidad',
          ],
          answer: 2,
        },
        {
          id: 'e30',
          tema: 'TEMA III',
          text: "En legislación comparada, la 'manipulación de sistemas' como el RUAT en Bolivia para evasión de impuestos se asemeja al tipo penal de:",
          opts: [
            'Estafa informática agravada por uso de sistemas públicos',
            'Violación de correspondencia electrónica',
            'Acceso ilícito a sistemas de organismos públicos con agravante',
            'Interceptación de comunicaciones financieras',
          ],
          answer: 2,
        },
        {
          id: 'e31',
          tema: 'TEMA IV',
          text: 'La Ley N° 1636 fue promulgada en Bolivia el:',
          opts: ['21 de febrero de 2023', '10 de septiembre de 2025', '15 de enero de 2024', '6 de agosto de 2022'],
          answer: 1,
        },
        {
          id: 'e32',
          tema: 'TEMA IV',
          text: 'El objeto de la Ley N° 1636 (Art. 1) es:',
          opts: [
            'Regular el comercio electrónico y la protección de datos personales en Bolivia',
            'Establecer un marco regulatorio para identificar, investigar y sancionar delitos contra la integridad sexual de NNA en entornos digitales',
            'Crear el sistema nacional de ciberseguridad y protección de infraestructura crítica',
            'Tipificar el acoso cibernético entre adultos como delito de acción pública',
          ],
          answer: 1,
        },
        {
          id: 'e33',
          tema: 'TEMA IV',
          text: 'La finalidad de la Ley 1636 (Art. 2) es proteger a toda niña, niño o adolescente generando mecanismos de:',
          opts: [
            'Investigación, procesamiento, condena y reinserción de agresores',
            'Prevención, protección, reparación y rehabilitación a las víctimas',
            'Detección, denuncia, sanción y eliminación de contenidos digitales',
            'Educación, sensibilización, capacitación y vigilancia digital',
          ],
          answer: 1,
        },
        {
          id: 'e34',
          tema: 'TEMA IV',
          text: "Según el Art. 4 de la Ley 1636, 'Niñas, Niños y Adolescentes' son:",
          opts: [
            'Personas menores de 16 años de edad',
            'Personas menores de 14 años según el Código NNA',
            'Personas hasta el cumplimiento de los 18 años de edad',
            'Personas menores de 21 años no emancipadas',
          ],
          answer: 2,
        },
        {
          id: 'e35',
          tema: 'TEMA IV',
          text: "Los 'Entornos Digitales' según el Art. 4 de la Ley 1636 comprenden:",
          opts: [
            'Únicamente internet y redes sociales con registro de usuarios',
            'Espacios de interacción a través de TIC, incluyendo internet, redes sociales, apps móviles, juegos en línea y plataformas virtuales',
            'Solo los medios de comunicación electrónica con sede en Bolivia',
            'Exclusivamente plataformas educativas virtuales autorizadas por el Estado',
          ],
          answer: 1,
        },
        {
          id: 'e36',
          tema: 'TEMA IV',
          text: "El 'Acoso Sexual en Entornos Digitales' (Art. 4, num. 6 Ley 1636) se define como conducta reiterada de intimidación que tiene por objeto:",
          opts: [
            'Obtener datos personales o información bancaria de la víctima',
            'Generar miedo, angustia o daño psicológico en la víctima',
            'Difundir imágenes íntimas de la víctima sin consentimiento',
            'Suplantar la identidad digital de una persona menor',
          ],
          answer: 1,
        },
        {
          id: 'e37',
          tema: 'TEMA IV',
          text: 'La Ley 1636 establece penas de hasta cuántos años por producir o difundir material de abuso sexual infantil:',
          opts: ['5 años', '10 años', '15 años', '20 años'],
          answer: 3,
        },
        {
          id: 'e38',
          tema: 'TEMA IV',
          text: 'El ámbito de aplicación de la Ley 1636 (Art. 3) alcanza a:',
          opts: [
            'Solo bolivianos residentes en territorio nacional',
            'Todas las bolivianas y bolivianos o extranjeras y extranjeros que se encuentren en el territorio del Estado Plurinacional de Bolivia y lugares sometidos a su jurisdicción',
            'Únicamente empresas de telecomunicaciones con sede en Bolivia',
            'Solo personas que cometan delitos a través de plataformas digitales con servidores en Bolivia',
          ],
          answer: 1,
        },
        {
          id: 'e39',
          tema: 'TEMA IV',
          text: "El 'Contenido Sexual' (Art. 4, num. 8 Ley 1636) es:",
          opts: [
            'Exclusivamente imágenes o videos con actos sexuales explícitos en internet',
            'Toda representación, descripción, imagen, comunicación o material real o simulado que involucra conductas sexuales explícitas o partes íntimas con fines sexuales',
            'Solo el material de abuso sexual infantil producido digitalmente',
            'Los mensajes con contenido sexual entre personas mayores de edad',
          ],
          answer: 1,
        },
        {
          id: 'e40',
          tema: 'TEMA IV',
          text: 'La Ley 1636 en cuanto a corresponsabilidad involucra en la protección de menores a:',
          opts: [
            'Únicamente al Estado y al Ministerio Público como entes persecutores',
            'Solo a las plataformas digitales y proveedores de internet',
            'Familias, instituciones educativas, empresas de comunicación y el Estado',
            'Exclusivamente a los padres y tutores legales de las víctimas',
          ],
          answer: 2,
        },
        {
          id: 'e41',
          tema: 'TEMA V',
          text: 'El Artículo 1 de la Constitución Política del Estado define a Bolivia como:',
          opts: [
            'Un Estado Federal Social de Derecho Democrático y Republicano',
            'Un Estado Unitario Social de Derecho Plurinacional Comunitario, libre, independiente, soberano, democrático, intercultural, descentralizado y con autonomías',
            'Una República Unitaria, Social y Democrática de Derecho',
            'Un Estado Plurinacional Federal con autonomías regionales',
          ],
          answer: 1,
        },
        {
          id: 'e42',
          tema: 'TEMA V',
          text: 'Los derechos reconocidos por la Constitución, según su Artículo 13 I, son:',
          opts: ['transferibles', 'inviolables', 'Universales', 'de Cumplimiento obligatorio'],
          answer: 1,
        },
        {
          id: 'e43',
          tema: 'TEMA V',
          text: 'El Artículo 13 num. IV de la CPE dispone que los tratados y convenios internacionales ratificados por la Asamblea Legislativa Plurinacional que reconocen derechos humanos:',
          opts: [
            'Tienen rango inferior a la Constitución pero superior a las leyes ordinarias',
            'Prevalecen en el orden interno y prohíben su limitación en los Estados de Excepción',
            'Son de aplicación facultativa según criterio del Tribunal Constitucional',
            'Solo son aplicables cuando el derecho interno no regule la materia',
          ],
          answer: 1,
        },
        {
          id: 'e44',
          tema: 'TEMA V',
          text: 'La Acción de Protección de Privacidad (habeas data) NO procede para levantar:',
          opts: [
            'El secreto bancario',
            'El secreto en materia de prensa',
            'El secreto en materia de seguridad nacional',
            'Toda clase de secreto profesional',
          ],
          answer: 1,
        },
        {
          id: 'e45',
          tema: 'TEMA V',
          text: 'El Art. 17 del Pacto Internacional de Derechos Civiles y Políticos establece que:',
          opts: [
            'Nadie será objeto de maltratos arbitrarios en su trabajo privado ni de ataques a su honra',
            'Nadie será objeto de injerencias arbitrarias o ilegales en su vida privada, familia, domicilio o correspondencia, ni de ataques ilegales a su honra y reputación',
            'Nadie será objeto de injerencias en su familia, trabajo o domicilio sin orden judicial',
            'Nadie será objeto de injerencias en su honra y reputación en casos no legislados',
          ],
          answer: 1,
        },
        {
          id: 'e46',
          tema: 'TEMA V',
          text: 'Los derechos digitales son conocidos también como:',
          opts: [
            'Derechos privados digitales',
            'Derechos personales informáticos',
            'Derechos digitales de las personas',
            'Derechos informáticos de los ciudadanos',
          ],
          answer: 2,
        },
        {
          id: 'e47',
          tema: 'TEMA V',
          text: 'La Conferencia de Estocolmo de 1967 determinó aspectos prácticos de la privacidad que protegen a los individuos de:',
          opts: [
            'Ataques a su identidad y trabajo',
            'Ataques a su familia y persona',
            'Ataques en su honra o reputación',
            'Ataques a su patrimonio económico',
          ],
          answer: 2,
        },
        {
          id: 'e48',
          tema: 'TEMA V',
          text: 'Los datos públicos, a diferencia de los datos sensibles, son:',
          opts: [
            'Estado de salud y costumbres sexuales',
            'Opiniones políticas y afiliación sindical',
            'Nombre y domicilio de fácil obtención y a disposición de todos',
            'Datos biométricos y registros genéticos',
          ],
          answer: 2,
        },
        {
          id: 'e49',
          tema: 'TEMA V',
          text: 'El Artículo 8 de la CPE establece como principios ético-morales de la sociedad plural:',
          opts: [
            'Ama qhilla, Ama llulla, Ama suwa (no seas flojo, no seas mentiroso ni seas ladrón)',
            'suma qamaña (vivir en paz), ñandereko (vida buena)',
            'Ama qhilla, Ama llulla, Ama suwa (no seas flojo, no seas envidioso ni seas ladrón)',
            'suma qamaña (vivir en armonía), ñandereko (vida noble)',
          ],
          answer: 0,
        },
        {
          id: 'e50',
          tema: 'TEMA V',
          text: 'Según Ossorio, el delito es definido como:',
          opts: [
            'Una acción típica, jurídica realizada por un ser humano, culpable y sancionada por una pena',
            'Una omisión típica, antijurídica realizada por un ser humano, culpable y sancionada por una pena',
            'Una acción típica, antijurídica realizada por un ser humano, culpable y sancionada por una pena',
            'Una acción típica, antijurídica realizada por la sociedad y el ser humano, culpable y sancionada por una pena',
          ],
          answer: 2,
        },
      ];

      // Remove duplicates by keeping unique text
      const seen = new Set();
      const LEGISLACION_QUESTIONS = ALL_QUESTIONS.filter((q) => {
        const key = q.text.slice(0, 60);
        if (seen.has(key)) return false;
        seen.add(key);
        return true;
      });
